apiVersion: v1
kind: ConfigMap
metadata:
  name: user-statistics-config
data:
  discovery-server-url: "user-statistics-service.default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-statistics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-statistics
  template:
    metadata:
      labels:
        app: user-statistics
    spec:
      containers:
        - name: user-statistics
          image: com.educatedcat.englishtelegrambot.user-statistics:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DISCOVERY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-config
                  key: server-url
            - name: DISCOVERY_ZONE
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-config
                  key: zone
            - name: DISCOVERY_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: user-statistics-config
                  key: discovery-server-url
            - name: ZIPKIN_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: base-url
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          startupProbe:
            initialDelaySeconds: 15
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-statistics-service
spec:
  selector:
    app: user-statistics
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
