server:
  port: 0

spring:
  application:
    name: user
  datasource:
    username: entb
    password: entb
    url: jdbc:postgresql://localhost:5432/entb_users
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: non-test
    change-log: db/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-productivity-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
  zipkin:
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1.0

kafka:
  topic:
    name: user-topic
