spring:
  application:
    name: dictionary
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: non-test
    change-log: db/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-productivity-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
  zipkin:
    sender:
      type: WEB
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    metadata-map:
      zone: ${DISCOVERY_ZONE:prod}
    lease-renewal-interval-in-seconds: 3
    hostname: ${DISCOVERY_HOSTNAME:localhost}

kafka:
  topic:
    name: user-productivity-topic

logging:
  level:
    com.educatedcat.englishtelegrambot.dictionary: DEBUG
