server:
  port: 0

spring:
  application:
    name: dictionary
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/entb_dictionary
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: non-test
    change-log: db/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  zipkin:
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1.0
