server:
  port: 0

spring:
  application:
    name: dictionary
  datasource:
    username: entb
    password: entb
    url: jdbc:postgresql://localhost:5432/entb_dictionary
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: non-test
    change-log: db/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  zipkin:
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1.0

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}::${random.value}
