spring:
  application:
    name: bot-sender
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: bot-message-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: org.telegram.telegrambots.meta.api.methods.*
  zipkin:
    sender:
      type: WEB
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    metadata-map:
      zone: ${DISCOVERY_ZONE:prod}
    lease-renewal-interval-in-seconds: 3
    hostname: ${DISCOVERY_HOSTNAME:localhost}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    url:
      api: ${TELEGRAM_BOT_API_URL}

kafka:
  message-sender:
    topic:
      name: bot-message-topic

logging:
  level:
    com.educatedcat.englishtelegrambot.botsender: DEBUG
