server:
  port: 8090

spring:
  application:
    name: bot-sender
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  zipkin:
    sender:
      type: WEB
  sleuth:
    sampler:
      probability: 1.0
