server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: bot-sender
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: bot-message-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: com.educatedcat.englishtelegrambot.kafkalib.serializer.CustomJsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: org.telegram.telegrambots.meta.api.methods.*

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}

eureka:
  client:
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    metadata-map:
      zone: ${DISCOVERY_ZONE:prod}
    lease-renewal-interval-in-seconds: 3
    hostname: ${DISCOVERY_HOSTNAME:localhost}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    url:
      api: ${TELEGRAM_BOT_API_URL}

kafka:
  message-sender:
    topic:
      name: bot-message-topic

logging:
  level:
    com.educatedcat.englishtelegrambot.botsender: DEBUG
  pattern:
    level: '%5p [%X{traceId:-},%X{spanId:-}]'
