apiVersion: v1
kind: Secret
metadata:
  name: bot-credentials
data:
  telegram_bot_api_url: aHR0cHM6Ly9hcGkudGVsZWdyYW0ub3JnL2JvdA==
  telegram_bot_token: NTQ1NTA2MDUxODpBQUdqVVFsNXhJMVQ5SHU0M01SMmdfZHF4VmMxUHNrUnVaUQ==
---