apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1-deployment
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: zookeeper-url
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: listener-security-protocol-map
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-1-service.default:9092,PLAINTEXT_INTERNAL://broker:29092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: TOPIC_AUTO_CREATE
              value: "false"
      volumes:
        - name: kafka-pv-volume
          persistentVolumeClaim:
            claimName: kafka-svc-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
spec:
  selector:
    app: kafka-1
  ports:
    - port: 9092
  type: ClusterIP
