server:
  port: 9090
spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: non-test
    change-log: db/changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
telegram:
  bot:
    username: username
    token: token
