server:
  port: 8090

spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

telegram:
  bot:
    username: entb_bot
    token: 5455060518:AAGHcfaL9bx5NFyAaxbUcKYkp6lJ8T0Rd4E

dictionary:
  url:
    api: http://localhost:8091/api

kafka:
  topic:
    name: user-productivity-topic
