server:
  port: 9090
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
telegram:
  bot:
    username: udemy_english_bot
    token: 1784447636:AAGnAq2R408rk-hNUvsTg3CO76UahWMoGaE
