apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-receiver-config
data:
  discovery-server-url: "bot-receiver-service.default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-receiver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-receiver
  template:
    metadata:
      labels:
        app: bot-receiver
    spec:
      containers:
        - name: bot-receiver
          image: com.educatedcat.englishtelegrambot.bot-receiver:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bot-receiver-postgres-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bot-receiver-postgres-conf
                  key: name
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bot-receiver-postgres-conf
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bot-receiver-postgres-credentials
                  key: postgres_bot_receiver_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-receiver-postgres-credentials
                  key: postgres_bot_receiver_password
            - name: TELEGRAM_BOT_API_URL
              valueFrom:
                secretKeyRef:
                  name: bot-credentials
                  key: telegram_bot_api_url
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-credentials
                  key: telegram_bot_token
            - name: DISCOVERY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: bot-receiver-config
                  key: discovery-server-url
            - name: DISCOVERY_ZONE
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-config
                  key: zone
            - name: DISCOVERY_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: discovery-server-config
                  key: hostname
            - name: ZIPKIN_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: zipkin-config
                  key: base-url
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
            - name: DICTIONARY_API_URL
              valueFrom:
                configMapKeyRef:
                  name: dictionary-config
                  key: api-url
            - name: SERVER_PORT
              value: '8080'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          startupProbe:
            initialDelaySeconds: 15
            failureThreshold: 10
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
      imagePullSecrets:
        - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bot-receiver-service
spec:
  selector:
    app: bot-receiver
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
