apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-receiver-postgres-conf
data:
  host: bot-receiver-postgres-service
  name: bot_receiver_db
  port: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: bot-receiver-postgres-credentials
data:
  postgres_bot_receiver_user: Ym90X3JlY2VpdmVyX3VzZXI=
  postgres_bot_receiver_password: dSV+M1hQZX1+QEYlZ25VQGpSJU14NFRkQWdUfTVGblo=
---
apiVersion: v1
kind: Service
metadata:
  name: bot-receiver-postgres-service
  labels:
    app: bot-receiver-postgres
    tier: database
spec:
  ports:
    - port: 5432
  selector:
    app: bot-receiver-postgres
    tier: database
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot-receiver-postgres-deployment
  labels:
    app: bot-receiver-postgres
    tier: database
spec:
  serviceName: bot-receiver-postgres
  replicas: 3
  selector:
    matchLabels:
      app: bot-receiver-postgres
  template:
    metadata:
      labels:
        app: bot-receiver-postgres
        tier: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: bot-receiver-postgres
          image: postgres:15.1
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bot-receiver-postgres-credentials
                  key: postgres_bot_receiver_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-receiver-postgres-credentials
                  key: postgres_bot_receiver_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: bot-receiver-postgres-conf
                  key: name
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: bot-receiver-postgres-persistence-storage
      volumes:
        - name: bot-receiver-postgres-persistence-storage
          persistentVolumeClaim:
            claimName: bot-receiver-postgres-pv-claim
